### ISSUE TITLE
Any chance for a Rev5 with Brook Zero PI Fighting Board

### ISSUE THREAD

**Issue by tdpssn** [jfedor2/flatbox#14]
It's a little cheaper to source than the Brook PS4/PS3 board and more current, though would take some work on the PCB design

**Comment by jfedor2** [comment]
From what I can see that board is PC/PS3/Switch only? Also quite large.

**Comment by MukiEX** [comment]
Yeah, the Fighting Zero board is better for assembling a full fightstick, as it's an easy manual setup with screw-in terminals. Kind of a moot point if you already have one with an Arduino or RP2040 option available.

Conceivably, one potential runner would be a LOLIN32 variant w/ a tiny LiPo battery for a wireless Switch/PC version.
