### ISSUE TITLE
Quick Question Regarding Resistors

### ISSUE THREAD

**Issue by piuzera** [jfedor2/flatbox#22]
Greetings!

First of all, thank you for this great project. I recently ordered 5 units from JLCPCB and unfortunately, they seem to be missing the R3 and R4 resistors. I can't power up and flash the memory because of this, most likely. I wish the reason is this, otherwise I just lost a ton of money :(

Below is an image of the PCB:

![PCBMissing](https://user-images.githubusercontent.com/11778557/189204239-db738051-fa64-46d7-be6e-3f9b0e327385.jpg)

Can you enlighten me on what resistor to buy for these slots? I will solder them myself to save the PCBs.

Thanks in advance!

**Comment by jfedor2** [comment]
My guess is that it won't make a difference.
