### ISSUE TITLE
Flatbox detected, buttons presses not registering

### ISSUE THREAD

**Issue by MorroMorro** [jfedor2/flatbox#25]
Hi J,

Put a switch on the board to test.  I added the firmware just fine. Windows is detecting it as flatbox rev4. 

Was detecting the button press just fine and then suddenly stopped. Now I've tried 3 boards, 5-6 switches, and non register the button presses. It was working then all of a sudden stopped, so I don't think it's a hardware issue. Any ideas I can try to troubleshoot this issue?

When I pull up the controller as a drive, should the uf2 file still be there? When I add it, it closes the drive. If I reopen it and it's no longer present. Not sure if that's as intended.

**Comment by jfedor2** [comment]
Yeah, the UF2 file copying works as you described, that's normal.

Are you testing the buttons in joy.cpl?

Have you tried alternative firmware like GP2040?

**Comment by MorroMorro** [comment]
Morning J. Yeah, I've been testing in joy.cpl. Flatbox looks amazing btw.

Will try alternate firmware and report back. For GP2040, hate to bother but I'm terrible at this stuff, do I just drop all the files and src folder from https://github.com/jfedor2/flatbox/tree/master/firmware-rp2040 onto the controller "drive"?

**Comment by MorroMorro** [comment]
No issue at all. I'm just bad at applying switches. J is a hero.

**Comment by jfedor2** [comment]
Glad to hear you got it working.

For future reference, the alternative GP2040 firmware can be downloaded from here:

https://github.com/FeralAI/GP2040/releases/download/v0.4.3/GP2040-FlatboxRev4_v0.4.3.uf2

And then you flash it the same way.

Let me know when you make the video!
