### ISSUE TITLE
Where is the circular button file

### ISSUE THREAD

**Issue by dron-one** [jfedor2/flatbox#41]
I can't find the 3D file of the button, only the shell, I am Xiao Bai, please tell me how to get this. Did you refer to the file again?

**Comment by marcelo-franceschini** [comment]
![image](https://github.com/jfedor2/flatbox/assets/34426867/04239acf-2e36-4d67-a46c-a0f9470dae59)

Did you take a look at the project's root folder?

**Comment by marcelo-franceschini** [comment]
Did you take a look at the project's root folder?


![image](https://github.com/jfedor2/flatbox/assets/34426867/04239acf-2e36-4d67-a46c-a0f9470dae59)

**Comment by dron-one** [comment]
谢谢您。但是按钮是两个脚的，我们按钮接口不是圆形十字的吗，接不上

**Comment by dron-one** [comment]
Thank you very much. But the button is two feet, our button interface is not round cross, can not connect

**Comment by marcelo-franceschini** [comment]
Two feet? 
Our button?
Are you using a translator to convert from an Asian language to English?

**Comment by dron-one** [comment]
This button requires a specific mechanical shaft to work。

**Comment by dron-one** [comment]
If you want to use a hot-swappable mechanical shaft, which make and model can be used?

**Comment by marcelo-franceschini** [comment]
The buttons would be the same model. You would change only the bottom piece.

![image](https://github.com/jfedor2/flatbox/assets/34426867/7781d0b3-c41a-4080-b015-d27bacf524f5)

**Comment by dron-one** [comment]
Got it. Thank you

**Comment by marcelo-franceschini** [comment]
> Got it. Thank you

You're welcome! Could you please close this issue? Thanks

**Comment by dron-one** [comment]
okThank you
