### ISSUE TITLE
Button mapping for tact switches

### ISSUE THREAD

**Issue by TheGor1lla** [jfedor2/flatbox#48]
Just soldered my own flatbox and tested out all the buttons.  For the 6 switches I get from left to right: Start, Back, none, none, L3, R3  

The soldering looks fine, but before I remove them I wanted to ask which buttons they are mapped to.

**Comment by jfedor2** [comment]
In XInput mode one of the remaining buttons is Guide (Home) and the other is not mapped. In PS4 mode it's Touchpad.

**Comment by TheGor1lla** [comment]
Home was blocked by my graphic cards software actions. Thanks for the answer!
