### ISSUE TITLE
PS4 8 Minute timeout with keys

### ISSUE THREAD

**Issue by linus-skold** [jfedor2/flatbox#59]
I upload the keys to the firmware and use it on a PS4 and i still get a timeout. 
Does the flatbox firmware not work with the auth keys or am I doing about this incorrectly.
It should be fairly straight forward to just select the right file and upload it. 

Any thoughts or known quirks around this ?

**Comment by jfedor2** [comment]
Probably best to try asking on the GP2040-CE Discord.

**Comment by linus-skold** [comment]
Well after some testing I can say that there's an issue with firmware version 0.7.8 and that the authentication doesn't work properly on that version. It's probably related to the full on rewrite they did of the authentication
