### ISSUE TITLE
Differences between Rev1 and Rev1.1

### ISSUE THREAD

**Issue by KaneBlueriverCL** [jfedor2/flatbox#6]
I saw the model was updated, I assume at a quick glance that the size of the case was standarized vs. newer revisions? If so, is the PCB size also changed? Thanks for your time!

**Comment by jfedor2** [comment]
That's right. Compared to rev1 the case is slightly narrower so it should now fit on Ender 3 printers. The PCB size also changed to accommodate this (rev1 and rev1.1 aren't compatible with regard to cases). There's more mounting screw holes and slightly more clearance above and below the PCB in the case.
