### ISSUE TITLE
Rev5 　none of the buttons work

### ISSUE THREAD

**Issue by yaaabooo** [jfedor2/flatbox#63]
Sorry for my poor English, but I need some help. 
I'm wondering why none of the buttons are connected to the GND. 
Is this ok? It works when connected to the GND.

![IMG_7352](https://github.com/user-attachments/assets/13f42212-c0e7-4d8d-8f46-f29fcbcdd291)

**Comment by jfedor2** [comment]
All the buttons are connected to GND on the bottom layer.

Make sure this soldering point is OK:

<img width="725" alt="Screenshot 2024-07-27 at 18 05 16" src="https://github.com/user-attachments/assets/0ed9180f-d268-4e35-8125-7df0c45fff13">

**Comment by yaaabooo** [comment]
I only saw the surface. 
now I understood the layer structure. And the cause was my soldering mistake. 
I appreciate your help.
