### ISSUE TITLE
Flatbox rev5 registering as Hori.Pokken controller

### ISSUE THREAD

**Issue by BusFinn** [jfedor2/flatbox#64]
I bought a rev5 flatbox online a year or so ago, it originally registered through steam that it was an Xbox controller but at some point it started registering as a horri.pokken controller. I’ve flashed the controller and done the updates on the controller and have had no luck. I would really like to use this on other consoles other than my PC but I don’t think it’ll work if it keeps registering as the horri.pokken controller.

**Comment by jfedor2** [comment]
You can switch modes by holding specific buttons while plugging the stick in or through webconfig.

https://gp2040-ce.info/usage/

**Comment by BusFinn** [comment]
Thanks, I’ll try that and get back to you

**Comment by BusFinn** [comment]
Yep that worked thanks so much!
