### ISSUE TITLE
Rev 2 additional material requirements 

### ISSUE THREAD

**Issue by huynhwi** [jfedor2/flatbox#7]
when making the rev2, the list of materials needed seem incomplete. It looks like you need a usb-c female header. Is there any other materials needed to make this board?

**Comment by jfedor2** [comment]
The USB connector is part of the SMT assembly BOM along with the ATmega32U4 chip and all the other components. If you order the PCB with SMT assembly from JLCPCB (or some other place) then you don't need to get those individual parts yourself. If you want to do the assembly yourself then sure, add the entire BOM to the list of parts needed.
